### PR TITLE
Adding travis + tests + fixing Python 3 installation

### PR DESCRIPTION
**Pull request by dfm**
I enabled testing using Travis: https://travis-ci.org/dfm/python-fsps

Right now the tests are fairly trivial but I got the build and import to work.

More tests should be added to `fsps/tests.py`.

### CODE REVIEW

**Comment by bd-j** [comment]
That is awesome!  Thanks @dfm.  I'll try and think up some useful tests when I get a chance.

**Comment by bd-j** [comment]
This looks good, and works for me.

I wrote a couple more tests (bd-j/python-fsps@2c8466c7f) After this PR is merged I can add them. I also have a couple code/documentation fixes for get_mags and the vactoair parameter.

**Comment by dfm** [comment]
Awesome. Shall we merge?

**Comment by bd-j** [comment]
yes!

**Pull request merged**
