### PR TITLE
Simplify installation procedure, use pygit2 so we don't depend on a runtime git

### PR DESCRIPTION
**Pull request by saethlin**
These changes should make it much easier for newcomers to install and use python-fsps. It obviates any need for editing the FSPS Makefile and prevents mysterious crashes if python-fsps can't find a git executable at runtime.

While the FSPS Makefile does now support parallel compilation (`make -j`), I've already run into build failures due to HPC filesystem inconsistency (gfortran says a `.mod` file is missing when it was definitely just generated) while working on this patch as a result of using `make -j`, so I don't use it here.

### CODE REVIEW

**Comment by saethlin** [comment]
I've also bumped the patch version, because I think these count as (albiet minor) bugfixes. It would be really nice if a new release were pushed to pypi as a result of this being merged (if it is).

**Comment by bd-j** [comment]
Do I understand right that this new `setup.py` file now actually recompiles FSPS instead of linking previously compiled modules?  That's a pretty substantial change to the installation procedure.

Also requirements should now include pygit2, yes?  Sorry for such a delayed response

**Comment by saethlin** [comment]
Yes, the changes as I have them recompile FSPS. Should be some logic to check if a recompilation is needed? Are people doing creative things with their linked FSPS that will be broken by a rebuild?

What is the role of the `requirements.txt` file? I added `pygit2` to the `setup_requires` section so `setuptools` should be able to handle everything I think, but I'm rather new to PyPI packaging requirements.

Just to be clear on my motivations here; I am submitting these changes in the hope of improving the workflow and onboarding within the group here. My groupmates are too often hindered by the need to work with Makefiles or Fortran code, to configure what is otherwise presented to them as a Python library. I've already submitted [this PR](https://github.com/cconroy20/fsps/pull/38) to FSPS which should get us out of editing Fortran source, and with this PR I want to (optionally?) remove manually running make (as well as the git papercut).

**Comment by bd-j** [comment]
This PR is not necessary with the new build system and FSPS submodule, where git is never used.  Closing

**Pull request closed without merging**
