### PR TITLE
use f2py via python rather than shell script

### PR DESCRIPTION
**Pull request by eteq**
This is a tweak to the setup script to have it run ``f2py`` programmatically instead of running in a separate shell process.

The motivation for this is that you can then be sure it's using the correct version of f2py on a system with mutliple pythons (or multiple numpys).  It figures this out just by doing ``from numpy.f2py import main``. Nominally the disadvantage is that it forces the use of the numpy version of f2py instead of an external version, but f2py has been in numpy for 7 or 8 years now, so I don't think that's a major problem.

Also, it's useful for systems the ``f2py`` scipy has a versioned name (macports, for example, creates ``f2py-2.7``, ``f2py-3.4`` and so on). That was my actual reason for doing this.

### CODE REVIEW

**Comment by dfm** [comment]
This looks great to me.

@jonathansick @bd-j any comments or should we merge?

Thanks Erik!

**Comment by jonathansick** [comment]
Yes! This is awesome. I've also noticed that even my pip-installs of numpy make a f2py2.7 binary so this would be perfect. I didn't know you could do that.

**Comment by bd-j** [comment]
This looks excellent.  Searching for the f2py binary has occasionally tripped me up.  Thanks Erik!

**Comment by jonathansick** [comment]
I just tried this out and it works perfectly. So I'll merge it and see if we can also get @bd-j's PRs merged too.

**Pull request merged**
